import { viewWidth } from "utils/functions";

const config = {
  animationSpeed: 1,
  backgroundColor: { space: "rgb", values: [0, 0, 0] },
  baseBrightness: -0.5,
  baseContrast: 0.8,
  bloomSize: 0.4,
  bloomStrength: 0.9,
  brightnessDecay: 1,
  brightnessOverride: 0,
  brightnessThreshold: 0,
  cursorColor: { space: "rgb", values: [0.9, 0.65, 1] },
  cycleFrameSkip: 4,
  cycleSpeed: 0.02,
  density: 1,
  ditherMagnitude: 0.05,
  effect: "palette",
  fallSpeed: 0.09,
  font: "matrixcode",
  forwardSpeed: 0.25,
  glintBrightness: -1.0,
  glintColor: { space: "rgb", values: [0.8, 0.6, 1] },
  glintContrast: 3.0,
  glyphEdgeCrop: 0,
  glyphHeightToWidth: 1,
  glyphMSDFURL: "/System/Matrix/assets/matrixcode_msdf.png",
  glyphSequenceLength: 57,
  glyphTextureGridSize: [8, 8],
  glyphVerticalSpacing: 1,
  hasBaseTexture: false,
  hasGlintTexture: false,
  hasThunder: false,
  highPassThreshold: 0,
  isPolar: false,
  isolateCursor: true,
  isolateGlint: false,
  isometric: false,
  loops: false,
  numColumns: Math.max(Math.floor(viewWidth() / 15), 50),
  palette: [
    { at: 0, color: { space: "hsl", values: [0.77, 0.32, 0.2] } },
    { at: 0.5, color: { space: "hsl", values: [0.77, 0.32, 0.5] } },
    { at: 1, color: { space: "hsl", values: [0.77, 0.32, 0.8] } },
  ],
  raindropLength: 1.5,
  renderer: "regl",
  resolution: 1,
  rippleScale: 30,
  rippleSpeed: 0.2,
  rippleThickness: 0.2,
  skipIntro: true,
  slant: 0,
  useCamera: false,
  useHalfFloat: false,
  useHoloplay: false,
  volumetric: false,
};

export default config;
